// Where each Blackbaud query run in 2026 went. A static list from the SKY query list of 2026-10-09 (105 queries).
// Columns: query, folder, owner, last run, kind, what replaces it, report id when a report page replaces it.
export type QueryMapRow = [string, string, string, string, string, string, string];
export const QUERY_MAP: QueryMapRow[] = [
  ["YTD Daily Totals","Gifts","Technology","2026-09-08","report","2026 YTD Income","ytd-income"],
  ["Active Partners","RDD Queries","Technology","2026-08-20","report","Active, LYBUNT and lapsed partners","status"],
  ["Annual Givers (as of 3/31/2026)","RDD Reporting","Technology","2026-04-08","report","Active, LYBUNT and lapsed partners","status"],
  ["LYBUNT Partners","RDD Queries","Technology","2026-08-13","report","Active, LYBUNT and lapsed partners","status"],
  ["Lapsed Partners","RDD Queries","Technology","2026-08-13","report","Active, LYBUNT and lapsed partners","status"],
  ["Annual Tax Receipts - EMAIL","Accountant Queries","Technology","2026-01-14","report","Annual tax receipt lists","tax"],
  ["Annual Tax Receipts - MAIL","Accountant Queries","Technology","2026-01-14","report","Annual tax receipt lists","tax"],
  ["Annual Tax Receipts - OTHERS","Accountant Queries","Technology","2026-01-14","report","Annual tax receipt lists","tax"],
  ["Email list builder CSVs","Constituents","Technology","2026-05-11","report","Appeal mailing list","mailing"],
  ["Florida ZIP Codes for Terry (1/2/2026)","Personal folder","Technology","2026-01-02","report","Appeal mailing list","mailing"],
  ["Rhode Islander Constituents (Fall 2024 visits)","David Morton","Technology","2026-07-07","report","Appeal mailing list","mailing"],
  ["Constituents with Active Email Addresses","Data Health/Maintenance","Technology","2026-02-23","report","Contact data lists","contact"],
  ["Constituents with No Email Address","Data Health/Maintenance","Technology","2026-02-23","report","Contact data lists","contact"],
  ["Constituents with No Valid Email","Data Health/Maintenance","Technology","2026-02-23","report","Contact data lists","contact"],
  ["New Constituents for ResearchPoint","Jerry Christian Queries","Jerry","2026-04-20","report","Contact data lists","contact"],
  ["Newly Added Constituents","Jerry Christian Queries","Jerry","2026-04-17","report","Contact data lists","contact"],
  ["Online Express email signups","General","Jerry","2026-05-04","report","Contact data lists","contact"],
  ["Daily Revenue Reporter 1.0 (Old version)","Routine Report Queries","Technology","2026-02-11","report","Daily Revenue Report","daily-revenue"],
  ["Daily Revenue Reporter 2.0 (Old version)","Routine Report Queries","Technology","2026-03-16","report","Daily Revenue Report","daily-revenue"],
  ["Daily Revenue Reporter 3.0 (Old version)","Routine Report Queries","Technology","2026-03-31","report","Daily Revenue Report","daily-revenue"],
  ["Daily Revenue Reporter 4.1","Routine Report Queries","Technology","2026-09-04","report","Daily Revenue Report","daily-revenue"],
  ["Foundations List","Michael Hinton","Michael","2026-06-02","report","Foundations","foundations"],
  ["List of Foundations (2025 giving)","RE NXT Lists","Jordan","2026-02-03","report","Foundations","foundations"],
  ["Partner foundations (highest to lowest)","Grant Services","Technology","2026-03-12","report","Foundations","foundations"],
  ["$5,000 and Up- Dynamic for Stephanie","Grace's Queries","Michael","2026-10-09","report","Gifts of $5,000 and up","large-gifts"],
  ["$5k+ Last Month","Michael Hinton","Technology","2026-07-09","report","Gifts of $5,000 and up","large-gifts"],
  ["$5k+ Partner Query","Support Team","Technology","2026-01-02","report","Gifts of $5,000 and up","large-gifts"],
  ["YTD GIFT gifts- 1/1/26- 5/12/26","RE NXT Lists","Michael","2026-05-12","report","Gifts of $5,000 and up","large-gifts"],
  ["RDD Action Reporting","RDD Reporting","Jerry","2026-08-26","report","KPI dashboard, RDD team",""],
  ["Full Portfolio Template","Constituents","Technology","2026-09-18","report","Portfolio export","portfolio"],
  ["Partner Data Template","Constituents","Technology","2026-02-09","report","Portfolio export","portfolio"],
  ["Stephanie Brady - portfolio (current)","Grace's Queries","Technology","2026-06-10","report","Portfolio export","portfolio"],
  ["Prayer List","Michael Hinton","Crystal","2026-09-30","report","Prayer list","prayer"],
  ["Campaign Performance Matrix Data","Acquisition Processes","Technology","2026-02-03","report","Results by appeal","appeal-results"],
  ["Carole's email list (IN PROGRESS)","Support Team","Technology","2026-08-28","report","Six-week email list","carole-list"],
  ["To calc Month-to-Date Recurring Gift Totals","Routine Report Queries","Technology","2026-03-30","report","Weekly recurring report","weekly-recurring"],
  ["Michael's Unfinished Actions","Michael Hinton","Technology","2026-09-11","report","Work Center (Your day)",""],
  ["Constituents for Actions - ALL","Partner Care","Jerry","2026-10-09","wc","Work Center",""],
  ["Constituents for Actions - Brian Carr","Partner Care","Technology","2026-09-17","wc","Work Center",""],
  ["Constituents for Actions - Celeste Paul","Partner Care","Technology","2026-01-09","wc","Work Center",""],
  ["Constituents for Actions - Church Engagement","Partner Care","Technology","2026-09-17","wc","Work Center",""],
  ["Constituents for Actions - David Morton","Partner Care","Jerry","2026-09-17","wc","Work Center",""],
  ["Constituents for Actions - Partner Care","Partner Care","Jerry","2026-08-03","wc","Work Center",""],
  ["Constituents for Actions - Richard Brown","Partner Care","Technology","2026-09-17","wc","Work Center",""],
  ["Constituents for Actions - Stephanie Brady","Partner Care","Technology","2026-07-20","wc","Work Center",""],
  ["100 Largest Churches - Midwest Region","Josh Milliron","Technology","2026-02-24","brain","Favor Brain list, not a saved report",""],
  ["100 Largest Churches - NE Region","Josh Milliron","Technology","2026-02-24","brain","Favor Brain list, not a saved report",""],
  ["100 Largest Churches - SE Region","Josh Milliron","Technology","2026-02-24","brain","Favor Brain list, not a saved report",""],
  ["100 Largest Churches - South Region","Josh Milliron","Technology","2026-02-24","brain","Favor Brain list, not a saved report",""],
  ["100 Largest Churches - West Region","Josh Milliron","Technology","2026-02-24","brain","Favor Brain list, not a saved report",""],
  ["Josh's Influenced Giving","Josh Milliron","Technology","2026-04-01","brain","Favor Brain list, not a saved report",""],
  ["RDD Retreat - Hard Credit Donors","RDD Reporting","Jerry","2026-04-08","brain","Favor Brain list, not a saved report",""],
  ["RDD Retreat - Soft Credit Donors","RDD Reporting","Jerry","2026-04-08","brain","Favor Brain list, not a saved report",""],
  ["Top Givers Test 2026","Michael Hinton","Michael","2026-07-09","brain","Favor Brain list, not a saved report",""],
  ["jordan 1","Grace's Queries","Grace","2026-02-02","brain","Favor Brain list, not a saved report",""],
  ["Actions to delete 11/10/25","Michael Hinton","Michael","2026-04-13","oneoff","One-off clean-up, not rebuilt",""],
  ["Actions to delete 2/23/26","Michael Hinton","Michael","2026-03-18","oneoff","One-off clean-up, not rebuilt",""],
  ["*CED Gift Data (old KPI Reporting sheet)","Gift Processing","Technology","2026-10-05","machine","Morning run (no staff report)",""],
  ["*CED Partners (Old KPI Reporting Sheet)","Gift Processing","Technology","2026-10-05","machine","Morning run (no staff report)",""],
  ["*temp nons","Daily Procedures - Partner & Gift Assignments","Technology","2026-08-05","machine","Morning run (no staff report)",""],
  ["*temp test for gifts audit","Gift Processing","Technology","2026-09-10","machine","Morning run (no staff report)",""],
  ["01 - Constituent Records","Import & Review New Constituent Processes","Technology","2026-10-02","machine","Morning run (no staff report)",""],
  ["02 - Constituent Actions","Import & Review New Constituent Processes","Technology","2026-09-27","machine","Morning run (no staff report)",""],
  ["03 - Contact Info Update (to the import updates)","Import & Review New Constituent Processes","Technology","2026-07-09","machine","Morning run (no staff report)",""],
  ["Assignments for Import (Upsert)","Cloudflare Data Sync Helper Queries","Technology","2026-08-24","machine","Morning run (no staff report)",""],
  ["BR: Open Proposals","Business Rules","Technology","2026-07-14","machine","Morning run (no staff report)",""],
  ["Blank PC gifts check","Gift Processing","Technology","2026-09-01","machine","Morning run (no staff report)",""],
  ["Daily Constituent Assignments","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Export of Check Data","Gift Processing","Technology","2026-03-31","machine","Morning run (no staff report)",""],
  ["GDV Process 2.0 - Actions","Gift Processing","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["GDV Process 2.0 - Gifts","Gift Processing","Technology","2026-10-02","machine","Morning run (no staff report)",""],
  ["GDV Process 2.0 - Remove Tags (Global Change)","Gift Processing","Technology","2026-09-01","machine","Morning run (no staff report)",""],
  ["GDV Process 3.0 - Gifts","Gift Processing","Technology","2026-09-01","machine","Morning run (no staff report)",""],
  ["Gift Backups Reboot","Gift Processing","Technology","2026-08-04","machine","Morning run (no staff report)",""],
  ["Inactive and Lost Constituents","Business Rules","Technology","2026-10-05","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 01 - Partner Care","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 02 - Grant Team","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 03 - Down Under (CELESTE)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 04 - South (EMPTY)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 05 - West Region (BRIAN)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 06 - Southeast (EMPTY)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 07 - Midwest (STEPHANIE)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 08 - East (RICHARD)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Assign 09 - Churches Director","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 01 - Partner Care","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 02 - Grant Team","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 03 - Down Under (CELESTE)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 04 - South (EMPTY)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 05 - West (BRIAN)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 06 - Southeast (EMPTY)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 07 - Midwest (STEPHANIE)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 08 - East (RICHARD)","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts Unassign 09 - Churches Director","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 01 - Partners","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 02 - Churches","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 03 - Businesses","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 04 - Ministries","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 05 - Intls","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 06 - Schools","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Portfolio Gifts' Constituency 07 - Foundations","Daily Procedures - Partner & Gift Assignments","Technology","2026-10-09","machine","Morning run (no staff report)",""],
  ["Type: Recurring Gift","Gift Processing","Technology","2026-03-23","machine","Morning run (no staff report)",""],
  ["WH 2026-09-29 David Patron verification","Daily Procedures - Partner & Gift Assignments","Technology","2026-09-29","machine","Morning run (no staff report)",""],
  ["WH Luke transfer 20260929","Daily Procedures - Partner & Gift Assignments","Technology","2026-09-29","machine","Morning run (no staff report)",""],
  ["ZZZ - Gifts not Credited to a Fundraiser","Daily Procedures - Partner & Gift Assignments","Jerry","2026-10-05","machine","Morning run (no staff report)",""],
  ["ZZZ - Major Donors without Fundraiser Assignment","Daily Procedures - Partner & Gift Assignments","Jerry","2026-10-05","machine","Morning run (no staff report)",""]
];
