import asyncio, sys, json
sys.argv = [sys.argv[0], 'http://127.0.0.1:8837']
exec(open('e2e_room.py', encoding='utf8').read().split("async def main():")[0])
async def go():
    async with async_playwright() as p:
        b = await p.chromium.launch(channel='msedge', args=FAKE)
        hctx, host = await mk(b, 'host@favorintl.org', 'Hannah Price')
        await host.goto(BASE + '/meet/book/', wait_until='networkidle'); await host.wait_for_timeout(1500)
        await host.screenshot(path=OUT + 'book1-1440.png')
        await host.click('[data-team="Support Team"]'); await host.wait_for_timeout(300)
        n = await host.evaluate("() => document.querySelectorAll('.mt-person').length")
        check('team adds its members', n >= 3, n)
        await host.fill('#addp', 'ann@favorintl.org'); await host.click('#addbtn')
        await host.fill('#addp', 'nobody@favorintl.org'); await host.click('#addbtn')
        await host.click('[data-step="2"]'); await host.wait_for_timeout(2500)
        await host.screenshot(path=OUT + 'book2-1440.png')
        slots = await host.evaluate("() => document.querySelectorAll('.slot').length")
        check('four best times', slots == 4, slots)
        txt = await host.inner_text('.slots')
        print(txt[:300].replace('\n', ' | '))
        note = await host.inner_text('#mt-book')
        check('unreadable calendar noted', 'could not be read' in note)
        await host.click('.slot >> nth=0'); await host.click('[data-step="3"]'); await host.wait_for_timeout(500)
        await host.fill('#ttl', 'Support Team weekly'); await host.click('[data-rec="video"]'); await host.click('[data-repeat="weekly"]')
        await host.screenshot(path=OUT + 'book3-1440.png')
        await host.click('#confirm'); await host.wait_for_selector('.done-ic', timeout=15000)
        await host.screenshot(path=OUT + 'booked-1440.png')
        check('booked screen', 'is booked' in await host.inner_text('#mt-book'))
        log = json.load(open('Q:/work/favor-meet-p0/out/gstub.log.json'))
        ev = [l for l in log if '/events' in l['p'] and l['m'] == 'POST']
        check('calendar event created once with attendees', len(ev) == 1 and len(ev[0]['b']['attendees']) >= 3 and ev[0]['b']['recurrence'] == ['RRULE:FREQ=WEEKLY'], ev[0]['b'].get('attendees') if ev else None)
        r = await api(host, 'meetings?scope=upcoming')
        ms = [m for m in r['json']['meetings'] if m['title'] == 'Support Team weekly']
        check('9 weekly rooms (first + 8)', len(ms) == 9, len(ms))
        check('backup meet link stored', ms[0]['backupLink'].startswith('https://meet.google.com/'), ms[0]['backupLink'])
        await host.goto(BASE + '/meet/', wait_until='networkidle'); await host.wait_for_timeout(1500)
        await host.screenshot(path=OUT + 'home-booked-1440.png', full_page=True)
        # cancel the series
        host.once('dialog', lambda d: asyncio.ensure_future(d.accept()))
        await host.click('[data-cancel] >> nth=0'); await host.wait_for_timeout(1500)
        log = json.load(open('Q:/work/favor-meet-p0/out/gstub.log.json'))
        check('calendar event deleted on cancel', any(l['m'] == 'DELETE' for l in log))
        r = await api(host, 'meetings?scope=upcoming')
        left = [m for m in r['json']['meetings'] if m['title'] == 'Support Team weekly' and m['status'] == 'scheduled']
        check('series cancelled', len(left) == 0, len(left))
        # phone view of step 2
        pctx, ph = await mk(b, 'host@favorintl.org', 'Hannah Price', 390, 844)
        await ph.goto(BASE + '/meet/book/', wait_until='networkidle'); await ph.click('[data-team="Support Team"]'); await ph.click('[data-step="2"]'); await ph.wait_for_timeout(2000)
        await ph.screenshot(path=OUT + 'book2-390.png', full_page=True)
        side = await ph.evaluate("() => document.documentElement.scrollWidth > document.documentElement.clientWidth")
        check('no sideways scroll on phone', not side)
        await b.close()
    print('FAILED:', [n for n, ok in R if not ok] or 'none')
asyncio.run(go())
